/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentação;


import entidade.Associado;
import entidade.TipoAssociado;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.NAssociado;

/**
 *
 * @author Pedro
 */
public class Associado_Pesquisa extends javax.swing.JInternalFrame {
    
    JDesktopPane jDesktopPanePrincipal;
    /**
     * Creates new form Associado_Pesquisa
     */
    public Associado_Pesquisa() {
        initComponents();
        preencherTela();
    }
    public Associado_Pesquisa(JDesktopPane jDesktopPanePrincipal){
        this();
        
        this.jDesktopPanePrincipal = jDesktopPanePrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisar = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();

        jTablePesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTablePesquisarMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisar);

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonFechar)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButtonFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        try {
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jTablePesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisarMousePressed
        try {
            int linha = jTablePesquisar.getSelectedRow();
            String codigo = jTablePesquisar.getValueAt(linha,0).toString();
            
            Associado asso = new NAssociado().consultar(Integer.parseInt(codigo));
            Associado_Cadastro tela04 = new Associado_Cadastro(jDesktopPanePrincipal, asso);
            
            jDesktopPanePrincipal.add(tela04);
            tela04.setVisible(true);
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTablePesquisarMousePressed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisar;
    // End of variables declaration//GEN-END:variables
    public void preencherTela(){
        try {
            //criando  o cabecalho da tabela
            Vector<String> cabecalho = new Vector();
            cabecalho.add("Identificador");
            cabecalho.add("Nome");
            cabecalho.add("Cpf");
            cabecalho.add("Rg");
            cabecalho.add("Telefone");
            cabecalho.add("Endereço");
            cabecalho.add("TipoAssociado");
            
            Vector detalhes = new Vector();
            for(Associado detalhe : new NAssociado().listar()){
                //criando  linha da tabela
                Vector<String> linha = new Vector();
                linha.add(detalhe.getCodigo() + "");
                linha.add(detalhe.getNome());
                linha.add(detalhe.getCpf());
                linha.add(detalhe.getRg());
                linha.add(detalhe.getFone() + "");
                linha.add(detalhe.getEndereco());
                linha.add(detalhe.getTipoAssociado().getDescricao() + "");
                detalhes.add(linha);
            }
            jTablePesquisar.setModel(new DefaultTableModel(detalhes, cabecalho));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
}
